.PHONY: clean All

All:
	@echo "----------Building project:[ smClient - Debug ]----------"
	@cd "smClient" && "$(MAKE)" -f  "smClient.mk"
clean:
	@echo "----------Cleaning project:[ smClient - Debug ]----------"
	@cd "smClient" && "$(MAKE)" -f  "smClient.mk" clean
