.PHONY: clean All

All:
	@echo "----------Building project:[ smClientJava - Debug ]----------"
	@cd "smClientJava" && "$(MAKE)" -f  "smClientJava.mk"
clean:
	@echo "----------Cleaning project:[ smClientJava - Debug ]----------"
	@cd "smClientJava" && "$(MAKE)" -f  "smClientJava.mk" clean
